version: "3"
services:
  server:
   build: .
   restart: always
   ports:
   - 3030:8015
   depends_on:
   - mysqldb
  mysqldb:
   image: "spring-docker"
   restart: always
   ports:
      - 3308:3306
   environment:
    MYSQL_DATABASE: users
    MYSQL_USER: root
    MYSQL_PASSWOED: Puj#190dbp
   
   
      
  
   
     

